=== AlexeyAllen/ITMO2022/ITMO2022.MarkupLangs(HTML_XML)/ITMO2022.XML/ITMO2022.XML.Lab02/lessons_DTD.dtd
<!ELEMENT lessons (lesson+)>
<!ELEMENT lesson (LessonName, ProfSurname, Time, StartDate, EndDate)>
<!ELEMENT LessonName (#PCDATA)>
<!ELEMENT ProfSurname (#PCDATA)>
<!ELEMENT Time (#PCDATA)>
<!ELEMENT StartDate (#PCDATA)>
<!ELEMENT EndDate (#PCDATA)>

=== AlexeyAllen/ITMO2022/ITMO2022.MarkupLangs(HTML_XML)/ITMO2022.XML/ITMO2022.XML.Lab02/ITMO2022.XML.Lab02.lessons.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lessons SYSTEM "lessons_DTD.dtd">
<lessons>
<lesson>
	<LessonName>C#</LessonName>
	<ProfSurname>Petrov</ProfSurname>
	<Time>5 PM</Time>
	<StartDate>02.02.2023</StartDate>
	<EndDate>02.03.2023</EndDate>
</lesson>
<lesson>
	<LessonName>PHP</LessonName>
	<ProfSurname>Ivanov</ProfSurname>
	<Time>6 PM</Time>
	<StartDate>03.03.2023</StartDate>
	<EndDate>03.04.2023</EndDate>
	</lesson>
<lesson>
	<LessonName>C++</LessonName>
	<ProfSurname>Verhov</ProfSurname>
	<Time>5 PM</Time>
	<StartDate>04.04.2023</StartDate>
	<EndDate>04.05.2023</EndDate>
	</lesson>
</lessons>
